### ISSUE TITLE
README confusing/wrong regarding semver rules

### ISSUE THREAD

**Issue by Sciss** [scalacenter/sbt-eviction-rules#15]
It says:

> - `early-semver`: assumes the matched modules follow a variant of [Semantic Versioning](https://semver.org) that enforces compatibility within 0.1.z.
> - `semver-spec`: assumes the matched modules follow [Semantic Versioning Spec](https://semver.org) that assumes no compatibility within 0.1.z.

Both links are identical and lead to https://semver.org - which says, that `0.x.y` is compatible. It is unclear whether any of `early-semver` or `semver-spec` follow `0.x.y` compatibility, and what the difference between the two is. `no compatibility within 0.1.z.` doesn't seem to make sense, and would be the same as `strict`?

**Comment by julienrf** [comment]
From the [Semantic Versioning specification](https://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

The specification says that when the major version is 0, “anything MAY change at any time”. So, no compatibility guarantees between releases (e.g., between 0.4.0 and 0.4.1). This is `semver-spec`.

However, in Scala we [recommend](https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#recommended-versioning-scheme) to keep binary compatibility between releases that have the same minor versions when the major version is 0 (e.g. between 0.4.0 and 0.4.1). This is `early-semver`.

Does that help?

**Comment by Sciss** [comment]
I see. Then I would suggest that the main information, compatibility within `1.x.y` is missing from the README. At least I find it confusing.

**Comment by Sciss** [comment]
And a related question. If scala-modules, e.g. scala-xml, scala-swing, are published with binary compatibility within `1.x.y`, e.g. scala-xml 1.2.0 is compatible with 1.3.0, what kind of `versionScheme` would cover this?

**Comment by julienrf** [comment]
This is conform to both `early-semver` and `semver-spec`, as those versioning schemes differ only about versions having 0 as major number.

**Comment by Sciss** [comment]
Well, as said, I think the README could clarify this, instead of relying on external links. It can be easily mistaken, if one is not interpreting `0.` in a particular manner.
